export default [
    "Do you think this is an offer of apparent control over the future?",
    "Could this also be a scheme?",
    "What will you eat tomorrow? ",
    "Next year? What then? ",
    "And also later…. What's later?",
    "And then the day after tomorrow …. What's then? ",
    "Do you evaluate every option carefully?",
    "Are you calculating the best solution?",
    "Do you sign and pay?",
    "Or sing and play? ",
    "Do you have plans for today? ",
    "You mean plants? ",
    "Have you forgotten to water the plans? ",
    "Are you free tonight? ",
    "You wanna go out for dinner sometime? ",
    "How long are you staying? ",
    "When do you have to get to the airport?",
    "How many times you have to change?",
    "Where will you pee?",
    "In which bed you want to sleep?",
    "What if you miss the departure?",
    "What if it rains?",
    "What if it's cold? ",
    "What if the car needs fuel? ",
    "Let's review some recent facts",
    "Do you have everything you need? ",
    "Do you drink enough water?",
    "And then what?",
    "When was the last time you cried in peace/public? ",
    "Are you alright? ",
    "And the next weeks, how is it then? ",
    "Do you want to plan a summer vacation together?",
    "When the Semester ends, what you gonna do? ",
    "How you gonna travel back? ",
    "And when? ",
    "How do you pay for your room? ",
    "How long you stay in one place before anyone notices?",
    "Is it ok if Ralph and Shiva come for New Year's eve? ",
    "How do you think things will develop? ",
    "Will you just wait and see? ",
    "Will you cross that bridge when you get there? ",
    "And then, when you meet all the familiar faces? ",
    "What will have changed? ",
    "And how will they ask you? ",
    "How will you ask them? ",
    "How do you like it here? ",
    "Whats diffrent? ",
    "How long will you stay here? ",
    "When will you return? ",
    "What's your field of study? ",
    "Do your teeth also hurt when the weather changes? ",
    "The dentist appointment is in 13 month ",
    "Would you ever like to go back to how it was before? ",
    "And how much would you sacrifice to make the impossible happen?",
    "Would it change everything? ",
    "Should we all go for a walk before it gets dark? ",
    "But but but can I also walk when it's dark? ",
    "I have something impoooortant to discuss with you- Lezz meet!",
    "Will you find a flight at the right time to the right place? ",
    "Is every new information a model character for further consideration?",
    "Does the planning process usually proceed in several stages as a sequence of phases?",
    "Please actively help to shape the future in a particular area!",
    "You think you could reduce the multilayered effects of planning to decisive functions?",
    "Maybe the early warning function? ",
    "Could it help to structure the problem? ",
    "Make corrections, reconcile/exchange subject and object or leave them alone.. ",
    "Thought of perception, definition and solution approaches?",
    "Do you also loose orientation sometimes? ",
    "You can always extend the scope of action you know ",
    "Coordination is important! ",
    "Then, will there be mutual dependencies across several levels?",
    "And a resolution of conflicts of distribution and interests?",
    "Will simplification bear the risk of inadequate representation?",
    "You know that nothing can be for granted?",
    "What will be reality?",
    "What is there to expect?",
    "What is there and what could be there ? ",
    "Can you define your goals?",
    "Did you budget your work?",
    "Did you commit?",
    "Are there established initial conditions?",
    "Boundaries to be considered?",
    "Are there given termination conditions? ",
    "Or elementary subsequent conditions?",
    "Will it lead to misjudgment? ",
    "Or an overall outcome dissatisfaction? ",
    "And if the planner (me/you/they/them), unaware of the process overlooks the fact that there are further chains of sequential processes, branches, And/or mergers …what will happen then?",
    "Who can help? Who will solve? Who will take care? ",
    "And how safe will be the automatic checking procedures? ",
    "Can they detect formal errors, such as loops or impossible scheduling? ",
    "Such as loops or impossible scheduling? ",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "Such as loops or impossible scheduling?",
    "On the other hand, will it require? ",
    "And when the planning ages..",
    "Will a particular problem arise?",
    "Will the financial, social and technical details be forming the progress of knowledge?",
    "Is it to be expected that both the time, money and resource requirements will be estimated to change with the passage of time based on the formulated requirements (specifications) ",
    "Or, generally a revised plan will show growth in all of these characteristics?",
    "Will you have the discipline to separate the unavoidable from the desirable? ",
    "(changes to continue to follow the plan?) ",
    "Overall, the planning must be updated",
    "So: continuous updating",
    "Then, enforcement ",
    "Will there be an ever-increasing variety of adversities?",
    "And will the creator/s recognise it as such? ",
    "When will the plan be recognised as unfeasible? ",
    "Such as loops or impossible scheduling?",
    "Must it first be enforced at every step against the adversities? ",
    "Sure, you can use all the tools that allow early signs to be better perceived-",
    "The signs may be: different allocation of scheduled resources ",
    "Or, different prioritisation and chaining ",
    "Also, alleged technical impossibilities  ",
    "Or, allegedly wrong conditions..",
    "Do you still have everything under control? ",
    "Do you now the main pitfall of planning? ",
    "The lack of flexibility and creativity in an action plan can significantly affect things",
    "However..are you being safe? ",
    "Do you now how to do the right thing? ",
    "Or the wrong thing? ",
    "Such as loops or impossible scheduling?",
    "Or the thing in between that is neither right nor wrong, because sometimes there might be no such thing as? ",
    "Did you make a list? ",
    "Did you ask someone for advice?",
    "And what will you do then? ",
    "And also later.. what's later? ",
    "You gonna wait some more? ",
    "Do you think better times are coming? ",
    "Could you ever bravely reach the point where there is no turning back? ",
    "Or, the topic being unfolded so far that something has to be performed now? ",
    "Fyi, anything can be conducted somehow..",
    "But how can anyone know?",
    "How can I be calm?",
    "How can anyone be calm?",
    "Are you sure that an orderly and efficient manner is appropriate? ",
    "How will everything be? ",
    "You really want to decide in advance what is to be done? ",
    "And when? And why? And by whom?",
    "How do you sleep at night? ",
    "Such as loops or impossible scheduling?",
    "And when something is over, how do you feel? ",
    "Do you ever pretend like nothing happened? ",
    "Do you sometimes deny things? ",
    "Do you ignore things/facts?",
    "And instead rely on opinions and/or hunches? ",
    "Do you sometimes black things out?",
    "If I look closely, might I catch you taking things too seriously?",
    "Or see you stubbornly holding on to something that might never be/work/happen?",
    "And if someone asks you, will you respond? ",
    "Are there things without a use?",
    "Do you think, when something unfortunate or unexpected happens, you can just deal with it? ",
    "That you could take it easy? ",
    "What are you doing here? ",
    "Did you consider all the things that should definitely be considered carefully? ",
    "Do you even want to see your visions turned into reality?",
    "Such as loops or impossible scheduling?",
    "And did you also know that the more lavish the plans blossom, the more tricky the action becomes?",
    "Why are you here? ",
    "Could you be inspired in the phase of the impossible? ",
    "Or by the obvious impossibility of knowing all of the things? ",
    "And still, I have the feeling we should meet!",
    "I prepared something and I want you to see it! ",
    "You land on a large air cushion and therefore can rehearse tricks safely. ",
];