export default [
    "Where does a thought go when it's forgotten?",
    "Could this be an offer of apparent control over the future?",
    "Is this a scheme?",
    "Who are you and what are your qualifications? ",
    "What will be tomorrow? ",
    "Next year? What then? ",
    "And also later…. What's later?",
    "And then the day after tomorrow …. What's then? ",
    "Do you evaluate every option carefully?",
    "To what degree are you able to control the course? (Or yourself)?",
    "Are you calculating the best solution?",
    "Do you have plans for today? ",
    "Do you mean plants? ",
    "Have you forgotten to water the plans? ",
    "Are you free tonight? ",
    "What day is today (beyond its invented name)? ",
    "You wanna go out for dinner sometime? ",
    "How long are you staying? ",
    "Do you ever wonder? ",
    "What would be ideal…. …for you personally? ",
    "When do you have to get to the airport?",
    "How many times you have to change?",
    "Where will you pee?",
    "In which bed you want to sleep?",
    "What if you miss the departure?",
    "What if it rains?",
    "How often do you ask yourself: how did things get so bad? ",
    "What if it's cold? ",
    "When are you launching? ",
    "\"When will you deliver? \",",
    "What if the car needs fuel? ",
    "Let's review some recent facts",
    "Do you have everything you need? ",
    "What keeps you up at night? ",
    "Are you able to find the right words? ",
    "Do you drink enough water?",
    "Are you alright? ",
    "What could be a mission? ",
    "And the next weeks, how is it then? ",
    "And when? ",
    "What does alright even mean?",
    "How long do you stay in one place before anyone notices?",
    "Is it ok if Ralph and Shiva come for New Year's eve? ",
    "How do you think things will develop? ",
    "Will you just wait and see? ",
    "Will you cross that bridge when you come to it? ",
    "What will change soon? ",
    "How do you like it here? ",
    "Whats different? ",
    "How long will you stay here? ",
    "Whats your primary method of communication? ",
    "When will you return? ",
    "What is your field? ",
    "What's your favorite way to spend your day? ",
    "Do your teeth also hurt when the weather changes? ",
    "Would you ever like to go back to how it was before? ",
    "How much would you sacrifice to make the impossible happen?",
    "Would it change everything? ",
    "Should we all go for a walk before it gets dark? ",
    "I have something impoooortant to discuss with you- Lezz meet!",
    "Will you find a flight at the right time to the right place? ",
    "Can I also walk when it's dark?",
    "Are there any other topics to talk about? ",
    "Is every new information a model character for further consideration?",
    "Does the planning process usually proceed in several stages as a sequence of phases?",
    "Please actively help to shape the future in a particular area!",
    "Do you think you could reduce the multilayered effects of planning to decisive functions?",
    "Are you familiar with the early warning function? ",
    "What could help to structure the problem? ",
    "How will you know when you've reached the goal? ",
    "Make corrections, reconcile and/or exchange subject and object or leave them alone.. ",
    "Have you thought of perception, definition and solution approaches?",
    "Do you also loose orientation sometimes? ",
    "What song always gets you out on the dance floor? ",
    "You can always extend the scope of action you know..",
    "Coordination is important!",
    "Then, will there be mutual dependencies across several levels?",
    "Will there be a resolution of conflicts of distribution and interests?",
    "What are the most critical obstacles or constraints? ",
    "Will simplification bear the risk of inadequate representation?",
    "Do you know that nothing can be for granted?",
    "What will be reality?",
    "What is there to expect?",
    "Where do you get your news? ",
    "What is there and what could be there ? ",
    "Can you define your goals?",
    "Did you budget your work?",
    "Would you commit?",
    "Are there established initial conditions?",
    "Are there boundaries to be considered?",
    "Are there given termination conditions? ",
    "Are there elementary subsequent conditions?",
    "Will it lead to misjudgment? ",
    "And if the planner (me/you/they/them), unaware of the process overlooks the fact that there are further chains of sequential processes, branches, And/or mergers …what will happen then? ",
    "Will it lead to an overall outcome dissatisfaction? ",
    "Who can help? ",
    "Who will take care? ",
    "Who wants to solve all the exciting tasks? ",
    "On the other hand, will it require? ",
    "And when the planning ages..",
    "Will a particular problem arise?",
    "Will the financial, social and technical details be forming the progress of knowledge?",
    "Is it to be expected that both the time, money and resource requirements will be estimated to change with the passage of time based on the formulated requirements (specifications)?",
    "Or, generally a revised plan will show growth in all of these characteristics?",
    "Will you have the discipline to separate the unavoidable from the desirable? (changes to continue to follow the plan?) ",
    "Overall, the planning must be updated!",
    "So: continuous updating",
    "Why is there something instead of nothing? ",
    "Enforcement! ",
    "Will there be an ever-increasing variety of adversities?",
    "And will the creator/s recognize it as such? ",
    "When will the plan be recognized as unfeasible? ",
    "Must it first be enforced at every step against the adversities? ",
    "Sure, you can use all the tools that allow early signs to be better perceived-",
    "One sign could be: different allocation of scheduled resources ",
    "Another sign could be: different prioritization and chaining ",
    "What about the alleged technical impossibilities? ",
    "What about the allegedly wrong conditions..?",
    "Do you still have everything under control? ",
    "Do you now the main pitfall of planning? ",
    "The lack of flexibility and creativity in an action plan can significantly affect things!",
    "However..are you being safe? ",
    "Do you now how to do the right thing? ",
    "Or the wrong thing? ",
    "Or the thing in between, that is neither right nor wrong, because sometimes there might be no such thing as? ",
    "Did you make a list? ",
    "What is your personal passion in all of this?",
    "How could you best leverage the assets? ",
    "Did you ask someone for advice?",
    "What will you do then? ",
    "Where do you hide at a party?",
    "And also later.. what's later? ",
    "Will you wait some more? ",
    "Do you think better times are coming? ",
    "Could you turn a ‘no' into a ‘yes'?",
    "Are you following a main timeline?",
    "Could you ever bravely reach the point where there is no turning back? ",
    "Could the topic be unfolded so far that something has to be performed now? ",
    "Fyi, anything can be conducted somehow..",
    "But how can anyone know?",
    "How can you be calm?",
    "How can anyone be calm?",
    "Are you sure that an orderly and efficient manner is appropriate? ",
    "How will everything be? ",
    "Do you really want to decide in advance what is to be done? ",
    "And when? And why? And by whom?",
    "And when something is over, how do you feel? ",
    "Do you ever pretend like nothing happened? ",
    "Do you sometimes deny things? ",
    "Do you ignore things/facts?",
    "And instead rely on opinions and/or hunches? ",
    "Do you sometimes black things out?",
    "What areas should your team focus on? ",
    "If I look closely, might I catch you taking things too seriously?",
    "Could I see you stubbornly holding on to something that might never be/work/happen?",
    "And if someone asks you, will you respond? ",
    "Are there things without a use?",
    "Do you think, when something unfortunate or unexpected happens, you can just deal with it? ",
    "So, what is the truth?",
    "Could you take it very easy? ",
    "What happens if nothing will be successful? ",
    "What are you doing here? ",
    "Did you consider all the things, that should definitely be considered carefully? ",
    "Do you even want to see your visions turned into reality?",
    "And did you also know that the more lavish the plans blossom, the more tricky the action becomes?",
    "Why are you here? ",
    "Whats your opinion on this? ",
    "Could you be inspired in the phase of the impossible? ",
    "Could you be inspired by the obvious impossibility of knowing all of the things? ",
    "Was that everything?",
    "And still, I have the feeling we should meet!",
    "I prepared something and I want you to see it! ",
    "You land on a large air cushion and therefore can rehearse tricks safely. ",
    "How safe will be the automatic checking procedures? ",
    "Can they detect formal errors, such as loops or impossible scheduling? ",
    "Such as loops or impossible scheduling? ",
];